### ISSUE TITLE
有些 BUG

### ISSUE THREAD

**Issue by hrpzcf** [TAHD3R/Pomorodo-timer-GUI#1]
如下图
![fq](https://user-images.githubusercontent.com/58855572/193740290-fb850b54-51d8-4da2-8f64-7cacf9a55e8a.gif)

现在的源代码运行不起来，ui 资源路径都有 `./ui/`前缀，但源码仓库似乎并没有`ui`目录？
以下是运行过程中的警告和错误

`qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute and QSGRendererInterface::OpenGLRhi using QQuickWindow::setGraphicsApi before constructing QGuiApplication.

    Error 263 for command:
        close 15011.wav
    指定的设备未打开，或不被 MCI 所识别。
Failed to close the file: 15011.wav

    Error 263 for command:
        close 15011.wav
    指定的设备未打开，或不被 MCI 所识别。
Failed to close the file: 15011.wav

    Error 259 for command:
        play 15011.wav wait
    驱动程序无法识别指定的命令参数。

    Error 263 for command:
        close 15011.wav   
    指定的设备未打开，或不被 MCI 所识别。
Failed to close the file: 15011.wav
Exception in thread Thread-9 (Music):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "f:\Python\Pomorodo-timer-GUI\main.py", line 95, in Music
    playsound(self.ts.dir_music)
  File "C:\Python310\lib\site-packages\playsound.py", line 73, in _playsoundWin
    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))
  File "C:\Python310\lib\site-packages\playsound.py", line 64, in winCommand
    raise PlaysoundException(exceptionMessage)
playsound.PlaysoundException: 
    Error 259 for command:
        play 15011.wav wait
    驱动程序无法识别指定的命令参数。

    Error 259 for command:
        play 15011.wav wait
    驱动程序无法识别指定的命令参数。

    Error 263 for command:
        close 15011.wav
    指定的设备未打开，或不被 MCI 所识别。
Failed to close the file: 15011.wav
Exception in thread Thread-11 (Music):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "f:\Python\Pomorodo-timer-GUI\main.py", line 95, in Music
    playsound(self.ts.dir_music)
  File "C:\Python310\lib\site-packages\playsound.py", line 73, in _playsoundWin
    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))
  File "C:\Python310\lib\site-packages\playsound.py", line 64, in winCommand
    raise PlaysoundException(exceptionMessage)
playsound.PlaysoundException:
    Error 259 for command:
        play 15011.wav wait
    驱动程序无法识别指定的命令参数。

    Error 259 for command:
        play 15011.wav wait
    驱动程序无法识别指定的命令参数。

    Error 263 for command:
        close 15011.wav
    指定的设备未打开，或不被 MCI 所识别。
Failed to close the file: 15011.wav
Exception in thread Thread-14 (Music):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "f:\Python\Pomorodo-timer-GUI\main.py", line 95, in Music
    playsound(self.ts.dir_music)
  File "C:\Python310\lib\site-packages\playsound.py", line 73, in _playsoundWin
    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))
  File "C:\Python310\lib\site-packages\playsound.py", line 64, in winCommand
    raise PlaysoundException(exceptionMessage)
playsound.PlaysoundException:
    Error 259 for command:
        play 15011.wav wait
    驱动程序无法识别指定的命令参数。

    Error 263 for command:
        close 15011.wav
    指定的设备未打开，或不被 MCI 所识别。
Failed to close the file: 15011.wav

    Error 263 for command:
        close 15011.wav
    指定的设备未打开，或不被 MCI 所识别。
Failed to close the file: 15011.wav

    Error 263 for command:
        close 15011.wav
    指定的设备未打开，或不被 MCI 所识别。
Failed to close the file: 15011.wav

    Error 263 for command:
        close 15011.wav
    指定的设备未打开，或不被 MCI 所识别。
Failed to close the file: 15011.wav`

**Comment by TAHD3R** [comment]
> ui 资源路径都有 ./ui/前缀，但源码仓库似乎并没有ui目录？

这里是上传时出现的问题，所有文件放在同一个目录里了，我会用正确的结构重新上传一次的~

**Comment by TAHD3R** [comment]
你好~我已经上传了正确文件结构的版本，并给之前的代码加上了注释。现在回头看看自己的代码有点太菜了，希望你别嫌弃呀。
